### ISSUE TITLE
Bot behaviour observations and ideas

### ISSUE THREAD

**Issue by sneakernets** [ioan-chera/AutoDoom#3] opened 2014-08-28 21:57 UTC
I played around with AutoDoom last night and wrote down some things.

A few suggestions going forward for Bot AI:
- **Emphasis on dodging Archvile attacks**. Archviles are one of the unique cases in the game.
- **Cannot find some key doors** - sometimes the bot will pass by a key door even after the bot has the required key. This could be due to the way the door is constructed in the map.
- **Bot attempts to pick up items it cannot collect.** This includes stimpacks and Green Armour, even if wearing Blue Armour.
- **Bot does not exit when given the opportunity:** This one is a bit weird. Sometimes on Doom E1M2, the bot will fight all the way to the exit, then turn around and go back through the dark maze area, attempting to pick up items it cannot currently collect, or doesn't need to collect, such as a stimpack when at 99% health.
- **Bot repeatedly gets stuck in barrels.** The bot needs to keep its distance from barrels as a means of survival unless the barrels are near an enemy, or blocking a picked objective, such as a teleport line, in that case, shooting the barrels from a distance.
- **Recessed switches are not always seen.** This one is a potential showstopper, since a lot of modern PWADs and IWADs starting from Doom 2 use this switch style. this can create a situation in which the bot currently "runs in place" or looks at a switch, runs to it, but never presses it.
- **Bot hesitates on jumping from some ledges.** This one is a bit strange. The bot points in the direction of the next objective, such as a key door, but if the ledge has some detailing (which can be assumed as always thanks to early 00's "Border-Mania" detailing) the bot will fail to leap.
- **Bot dancing in Co-op mode.** This usually happens when the bot grabs a key objective, such as the Yellow key on BTSX Ep1 MAP02. After picking up the key, the bot looks at the yellow key switch direction, the direction of the outer hallway, and the direction of the previous enemy killed. This could go on for hours. I assume it's because the key doesn't disappear! 
- **Projectile weapons cause issues.** Just what it says. The rocket launcher is a death wish for the bot right now. The Plasma gun is also a waste, as the bot will shoot the wall trying to hit an enemy if it is around the corner. BFG is actually useful like this, though.
- **Bot does not retreat when overwhelmed.** This is probably something you're already aware of. If the bot is surrounded, it needs to find a direction to run, either by ploughing through weaker monsters or running around tougher ones.
- **Bot still can get stuck in certain, unexplained places**. This is a catch-all, but I can't figure out why the bot gets stuck in the SSG room in Doom 2 MAP02. It just shouldn't happen, but it does, regardless of whether the bot collects the red key or not.

Those are all of the major ones. Some minor ones:
- **Item Priorities**. The bot doesn't need to collect ammo or health unless the max capacity/benefit of the item can be obtained. This would take care of the "picking up stimpack at 99% health" or picking up a box of bullets when at 199/399 bullets. Some cases might need exceptions, so maybe it'd be best to take the floor of the nearest 10, with some fudge range, e.g. picking up a stimpack when at 91% or 92% health is probably a good idea if the player can grab it during a fight. We could also could check for stuff like armour percentage and the class of armour the player has, so the Bot doesn't grab a green armour when he has 99% blue armour.
- **Real-time Bot Pondering Stats**. This would make it easier for testers to see what the bot is currently doing, what it plans to do, and certainty of the move it is pondering. Might be a lot of work.

**Comment by sneakernets** [comment] 2014-09-08 15:16
Another one I found: The bot has a lot of trouble navigating hallways and passageways with crushing ceilings, especially those in a series (Doom E2M2 comes to mind). With god mode on, it can take a little time to get through it.

The bot also has trouble activating lifts in small areas, attempting to "straferun" into it, but not at the right angle to trigger it.

**Comment by ioan-chera** [comment] 2015-08-13 15:53
Here are my comments on some of the points:
- Emphasis on dodging Archvile attacks: will be addressed when I work on combat AI. It needs to differentiate based on enemy attack sequences.
- Cannot find some key doors: might be caused by other missing features or bugs.
- Bot attempts to pick up items it cannot collect: the bot has to learn how much it gains from items and what are the upper limits. Until it knows, it will attempt to pick up unknown items of no effect. Unfortunately the learning code is not finished, and it won't act exactly correct with regard to this.
- Bot does not exit when given the opportunity: like in AutoWolf, it will prefer to explore the level before leaving it. It's debatable whether this is desired, especially in Doom.
- Bot repeatedly gets stuck in barrels: this should be addressed in the combat AI. Barrels are practically immobile monsters with explosive deaths, and need to be treated as such. Currently it attacks them like they're threatening enemies, which is not very good. It CANNOT treat them as static obstacles.
- Recessed switches are not always seen: this is a problem because the switch hit area is not trivial to determine and not implemented, and currently the bot just has a list of points in front of the switch. In the case of recessed switches, the points probably reside in an invalid area. There are probably other inaccuracies too.
- Bot hesitates on jumping from some ledges: unfortunately the bot has a tendency to pick the shortest route, even if it's on a slippery ledge. Making the bot move carefully to avoid falling off ledges is a tough problem for now.
- Bot dancing in Co-op mode: neither multiplayer, nor multiplayer-like item behaviour are implemented for the bot. They're definitely on the plan.
- Projectile weapons cause issues: will be addressed when I work on combat AI. The RL is challenging not only because of its risk, but also due to the rather big start-up delay.
- Bot does not retreat when overwhelmed: now it retreats from any nearby monster. It needs to be improved.
- Bot still can get stuck in certain, unexplained places: pathfinding problem. Likely due to unimplemented features such as jumping.

**Closed as completed** 2019-10-20 19:47 UTC
